#!/usr/bin/env python

import psutil
import pyelasticsearch
from pyelasticsearch import *
import time

INDEX = 'psutils'
DOCTYPE = 'PS'

es  = ElasticSearch('http://localhost:9200/')
psd = psutil.disk_io_counters()
hostname = 'zeus'

doc = {
    'read_count': psd.read_count,
    'write_count': psd.write_count,
    'read_bytes': psd.read_bytes,
    'write_bytes': psd.write_bytes,
    'read_time': psd.read_time,
    'write_time': psd.write_time,
    'hostname': hostname,
    'timestamp': time.time()
    }

es.index(INDEX, DOCTYPE, doc)

