#!/usr/bin/env python

import psutil
import pyelasticsearch
from pyelasticsearch import *
import time
import socket
import ConfigParser


INDEX = 'psutils'
DOCTYPE = 'PS'
config = ConfigParser.ConfigParser()
config.read('psmond.cfg')

server = config.get('Server', 'server')
port = config.get('Server', 'port')
url = 'http://'+server+":"+port

es  = ElasticSearch(url)
psd = psutil.disk_io_counters()
hostname = socket.gethostname()

doc = {
    'read_count': psd.read_count,
    'write_count': psd.write_count,
    'read_bytes': psd.read_bytes,
    'write_bytes': psd.write_bytes,
    'read_time': psd.read_time,
    'write_time': psd.write_time,
    'hostname': hostname,
    'timestamp': time.time()
    }

es.index(INDEX, DOCTYPE, doc)

